const dadosComites = [
  {
    tema: "Estratégias Contra a Violência e a Violação aos Direitos Humanos no Futebol",
    comite: "Direitos Humanos",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjgxNjE4MDA0MzQ3?cjc=i72nikf",
    whatsapp: "https://chat.whatsapp.com/KTXEAgsedPbJATiJ7lsR1e",
    pdf: "https://drive.google.com/file/d/1QgfwpT_Ijbe2d_pub50pK5VebZsbT39s/view",
    idioma: "ptbr",
    imagem: "HR_Futebol.jpg",
  },
  {
    tema: "Violação dos Direitos Humanos no sistema carcerário de El Salvador",
    comite: "Direitos Humanos",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjUyODI2MjQ1NTIx?cjc=na7x4q3",
    whatsapp: "https://chat.whatsapp.com/GMtYLUsZxXP5htQ93Rlrpu",
    pdf: "https://drive.google.com/file/d/1J0mK5DhJSFp74f3w1bbtWy-LwB3k1aNr/view?usp=sharing",
    idioma: "ptbr",
    imagem: "HR_ElSalvador.png",
  },
  {
    tema: "Medidas Contra o Narcotráfico Internacional",
    comite: "Conselho de Segurança",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Njc2NTk5MzA1ODU1?cjc=mwudzt2",
    whatsapp: "https://chat.whatsapp.com/CjIpNTdJ38tCNQvjC3vkph",
    pdf: "https://drive.google.com/file/d/1RYOTlkmAlFvN11kpULv8sAtSfb5G3bbF/view",
    idioma: "ptbr",
    imagem: "SC_Narcotráfico.jpg",
  },
  {
    tema: "Regulação das Criptomoedas no Comércio Internacional",
    comite: "OMC (Organização Mundial do Comércio)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjgxNjE3OTM5Nzgy?cjc=wczy4do",
    whatsapp: "https://chat.whatsapp.com/B6xsZmeuyU6Hz5Os9UDRYa",
    pdf: "https://drive.google.com/file/d/1Mf7NhxH3ER-kD1EKCXqcZNu2-XUQlf8g/view",
    idioma: "ptbr",
    imagem: "OMC_Cripto.jpg",
  },
  {
    tema: "Mundialização e Reforma da Educação",
    comite:
      "UNESCO (Organização das Nações Unidas para a Educação, a Ciência e a Cultura)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjgxNjE3OTgyNTA0?cjc=gpbhakg",
    whatsapp: "https://chat.whatsapp.com/D3akV8iCTrzHXTIsOeJ6ob",
    pdf: "https://drive.google.com/file/u/6/d/1MEq7Xcngj7UjiVKfQLwz9UNaTcz2MGDi/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "UNESCO_Educação.jpg",
  },
  {
    tema: "Medidas de Mitigação da Escravidão Moderna no Circuito da Moda",
    comite: "OIT (Organização Internacional do Trabalho)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Njc2NTk5Mjg3MDg0?cjc=bhxtemp",
    whatsapp: "https://chat.whatsapp.com/Ew3WIYPxZrjE3MDWjSGvep",
    pdf: "https://drive.google.com/file/d/1Y1Lq4EQ0Rs1_9TGMiH6nXOOLa53oZie-/view",
    idioma: "ptbr",
    imagem: "OIT_Moda.jpg",
  },
  {
    tema: "Possibilidades de Reparação Histórica no Haiti",
    comite: "ECOSOC (Conselho Econômico e Social das Nações Unidas)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjUyODI2MjcxNDg4?cjc=f5dobyq",
    whatsapp: "https://chat.whatsapp.com/F2MACdg4hkn6HDbE7pgOa4",
    pdf: "https://drive.google.com/file/d/1uUrvBjVhDhIlFxekOlg1nJYWn91zcqj5/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "ECOSOC_Haiti.png",
  },
  {
    tema: "Discutindo a Preservação e Demarcação das Terras Indígenas na América",
    comite: "OEA (Organização dos Estados Americanos)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjgxNjE3OTU5NDkz?cjc=hs2emhn",
    whatsapp: "https://chat.whatsapp.com/DMBG1M33N0z1luneTN4ps2",
    pdf: "https://drive.google.com/file/u/6/d/1T-HWJjGJ7uX4xcFnYGsBJv6QswBOHXR1/view?usp=sharing",
    idioma: "ptbr",
    imagem: "OEA_Indígenas.png",
  },
  {
    tema: "Impactos da exploração de recursos naturais nos países africanos",
    comite: "PNUMA (Programa das Nações Unidas para o Meio Ambiente)",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/NjUyODI2Mzk5MDEy?cjc=iis74fj",
    whatsapp: "https://chat.whatsapp.com/E4MLyv6btyg1q64hyOwhUF",
    pdf: null, // Sem PDF
    idioma: "ptbr",
    imagem: "PNUMA_África.jpeg",
  },
  {
    tema: "Regulação do uso de feitiços e magias no mundo mágico da Disney",
    comite: "Comitê Especial - Disney",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Njc2NTk4OTE3NjEw?cjc=6rw33ar",
    whatsapp: "https://chat.whatsapp.com/EfFi9dzCk5x1k9oGRFO37I",
    pdf: "https://drive.google.com/file/u/6/d/14tYHTaZs8KNI40CzfsBPE8-5c1bU-uxI/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "Especial_Disney.jpg",
  },
  {
    tema: "The Impacts of the Arctic Militarization",
    comite: "Security Council",
    modalidade: "Double",
    classroom: "https://classroom.google.com/c/NjUyODI2NjAyMTM8?cjc=ogc5xrl",
    whatsapp: "https://chat.whatsapp.com/FeK1tjPPhLQECFgVfQkt2h",
    pdf: "https://drive.google.com/file/u/6/d/1Tx9W9NAUsOBsYbHZqFs1vGrq2rKIqoPr/view?usp=sharing",
    idioma: "en",
    imagem: "SC_ArcticMilitarization.jpg",
  },
  {
    tema: "Discussing the Aftermaths and the Future of the Korean War",
    comite: "Historical Security Council",
    modalidade: "Double",
    classroom: "https://classroom.google.com/c/NjgxNjE3Nzg5NDg8?cjc=fxq2bf7",
    whatsapp: "https://chat.whatsapp.com/EHLLPQjzBjk7wiKunObRIN",
    pdf: "https://drive.google.com/file/u/6/d/1GhzE5g_-NEZq5JTjxAWjbindIFyHIq3p/view?usp=drive_link",
    idioma: "en",
    imagem: "HSC_KoreanWar.jpg",
  },
  {
    tema: "The different consequences that are given to each Scuderia by FIA",
    comite: "Special Committee - FIA",
    modalidade: "Single",
    classroom: "https://classroom.google.com/c/NjgxNjE4MzI0MzE8?cjc=4zej4lp",
    whatsapp: "https://chat.whatsapp.com/GRnP77c8iBf9il6NbR9DrW",
    pdf: "https://drive.google.com/file/u/6/d/1E3umNYkY7JPchlOD_KCzkTuEuqOgfxEJ/view?usp=drive_link",
    idioma: "en",
    imagem: "Special_FIA.jpg",
  },
];

export default dadosComites;
